int  kbsetupdslide1callback(int val,int i,void *Tmp) ;
int  kbsetupdslide2callback(int val,int i,void *Tmp) ;
int  kbsetupbutton1callback(int butno,int i,void *Tmp) ;
void  kbsetupbutton1init(DIN *B,void *pt) ;
int  kbsetupbutton2callback(int butno,int i,void *Tmp) ;
void  kbsetupbutton2init(DIN *B,void *pt) ;
int  kbsetupsplbutton1callback(int butno,int i,void *Tmp) ;
void  kbsetupsplbutton1init(DIL *B,void *pt) ;
int  kbsetupbrowser1callback(int item,int i,void *Tmp) ;
void  kbsetupbrowser1init(DIRA *R,void *pt) ;
int  kbsetupbrowser2callback(int item,int i,void *Tmp) ;
void  kbsetupbrowser2init(DIRA *R,void *pt) ;
int  kbsetupbrowser3callback(int item,int i,void *Tmp) ;
int  kbsetupbrowser4callback(int item,int i,void *Tmp) ;
int  kbsetupbrowser5callback(int item,int i,void *Tmp) ;
void  kbsetupbrowser5init(DIRA *R,void *pt) ;
int  kbsetupbrowser6callback(int item,int i,void *Tmp) ;
void  kbsetupbrowser6init(DIRA *R,void *pt) ;
int  kbsetupbrowser7callback(int item,int i,void *Tmp) ;
void  kbsetupbrowser7init(DIRA *R,void *pt) ;
int  kbsetupdslide3callback(int val,int i,void *Tmp) ;
int kbsetupinit(void *Tmp) ;
int kbsetupcleanup(void *Tmp) ;
int Modifykbsetup(void *Tmp,int GrpId) ;
int kbsetupCallBack(void *Tmp,void *tmp) ;
int kbsetupResizeCallBack(void *Tmp) ;
int kbsetupWaitCallBack(void *Tmp) ;
